import React from 'react';
import { motion } from 'framer-motion';
import AlertsOverTime from './components/AlertsOverTime';
import AlertsBySourceIP from './components/AlertsBySourceIP';
import AlertsBySeverity from './components/AlertsBySeverity';
import AlertsByCategory from './components/AlertsByCategory';
import AlertsByProtocol from './components/AlertsByProtocol';
import AlertsBySignature from './components/AlertsBySignature';

const Dashboard = () => {
    return (
        <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            style={styles.container}
        >
            <motion.h1
                initial={{ y: -100, opacity: 0 }}
                animate={{ y: 0, opacity: 1 }}
                transition={{ delay: 0.2 }}
                style={styles.header}
            >
                Alert Dashboard
            </motion.h1>
            <motion.p
                initial={{ y: -50, opacity: 0 }}
                animate={{ y: 0, opacity: 1 }}
                transition={{ delay: 0.3 }}
                style={styles.description}
            >
                This dashboard is developed for the analysis of alerts generated by the Intrusion Detection System (IDS). It provides insights into various alert metrics such as category, severity, source IP, and more. The goal is to offer a comprehensive view of the security alerts to help identify patterns and prioritize responses.
            </motion.p>
            <motion.p
                initial={{ y: -50, opacity: 0 }}
                animate={{ y: 0, opacity: 1 }}
                transition={{ delay: 0.3 }}
                style={styles.description}
            >
                Using this dashboard, analysts can quickly pinpoint critical issues, track alert trends over time, and understand the origins and types of threats. Each card below represents a different aspect of the alert data, providing a multi-faceted approach to cybersecurity analysis.
            </motion.p>
            <motion.p
                initial={{ y: -50, opacity: 0 }}
                animate={{ y: 0, opacity: 1 }}
                transition={{ delay: 0.3 }}
                style={styles.owner}
            >
                Developed by Gurdeep Singh
            </motion.p>
            <div style={styles.alertsContainer}>
                <motion.div
                    initial={{ x: -100, opacity: 0 }}
                    animate={{ x: 0, opacity: 1 }}
                    transition={{ delay: 0.4 }}
                    style={styles.alertColumn}
                >
                    <AlertCard title="Alerts by Category">
                        <AlertsByCategory />
                    </AlertCard>
                    <AlertCard title="Alerts by Severity">
                        <AlertsBySeverity />
                    </AlertCard>
                </motion.div>
                <motion.div
                    initial={{ y: 100, opacity: 0 }}
                    animate={{ y: 0, opacity: 1 }}
                    transition={{ delay: 0.4 }}
                    style={styles.alertColumn}
                >
                    <AlertCard title="Alerts Over Time">
                        <AlertsOverTime />
                    </AlertCard>
                    <AlertCard title="Alerts by Source IP">
                        <AlertsBySourceIP />
                    </AlertCard>
                </motion.div>
                <motion.div
                    initial={{ x: 100, opacity: 0 }}
                    animate={{ x: 0, opacity: 1 }}
                    transition={{ delay: 0.4 }}
                    style={styles.alertColumn}
                >
                    <AlertCard title="Alerts by Protocol">
                        <AlertsByProtocol />
                    </AlertCard>
                    <AlertCard title="Alerts by Signature">
                        <AlertsBySignature />
                    </AlertCard>
                </motion.div>
            </div>
        </motion.div>
    );
};

const AlertCard = ({ title, children }) => (
    <div style={styles.alertCard}>
        <h2 style={styles.cardTitle}>{title}</h2>
        <div style={styles.cardContent}>
            {children}
        </div>
    </div>
);

const styles = {
    container: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        padding: '20px',
        backgroundColor: '#121212',
        color: '#ffffff',
        minHeight: '100vh',
    },
    header: {
        marginBottom: '10px',
        color: '#ffffff',
    },
    description: {
        marginBottom: '20px',
        fontSize: '16px',
        textAlign: 'center',
        maxWidth: '800px',
    },
    owner: {
        marginBottom: '30px',
        fontSize: '14px',
        textAlign: 'center',
        color: '#bbbbbb',
    },
    alertsContainer: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        width: '100%',
    },
    alertColumn: {
        width: '100%',
        display: 'flex',
        justifyContent: 'space-around',
        flexWrap: 'wrap',
        margin: '10px 0',
        alignItems: 'stretch', // Added align-items property
    },
    alertCard: {
        backgroundColor: '#1e1e1e',
        padding: '20px',
        borderRadius: '10px',
        boxShadow: '0 4px 8px rgba(0, 0, 0, 0.3)',
        marginBottom: '20px',
        flex: '1 1 220px', // Reduced flex basis from 300px to 250px
        margin: '10px',
        minWidth: '200px', // Reduced minWidth from 300px to 250px
        maxWidth: '40%', // Reduced maxWidth from 45% to 40%
    },
    cardTitle: {
        marginBottom: '10px',
        color: '#ffffff',
        fontSize: '18px',
        borderBottom: '1px solid #444',
        paddingBottom: '5px',
    },
    cardContent: {
        color: '#dddddd',
    },
};


export default Dashboard;
